### PR TITLE
Update plugin for new Mongoose

### PR DESCRIPTION
**Pull request by drugoi**

### CODE REVIEW

**Comment by agorem** [comment]
Hi, Nikita,
Thanks for your support.
I have reviewed the changes you are proposing and I have only one problem to commit.
You have introduced ES6 features (ie: const instead of var) in the code that can impose some usage limitations. Although I am usually using ES6 in my apps, it is still a good practice to maintain the ES5 syntax in modules.
If you update the files accordingly I will merge your changes.
Regards....Antonio

**Comment by drugoi** [comment]
Hi, Antonio!

Thanks for fast respond.

I can rewrite it back to ES5 syntax, but if we stricted node engines, do we really need to support old syntax? Travis checks doesn't failed and maybe it's a good start to write plugins in ES6?
Also, we don't use import/export and other non-standart or unstable features — [compat table](https://kangax.github.io/compat-table/es6/#node4)

But you a owner of this plugin and I will be glad to help and rewrite it back.

**Comment by agorem** [comment]
Hi, Nikita,

I understand your approach and I agree that the community should address the migration to fully ES6 compatible node version (9+) to use the ES6 syntax without the need of transpilers of compat options.

But in this case, **mongoose-i18n-neutral** is just a mongoose plugin and we should be consistent with the mongoose node version restrictions to avoid compatibility problems.

Currently mongoose stills supports node version 4.*+ and it is written using ES5 syntax.

So I prefer to avoid the ES6 syntax you have included (const/let and arrow functions).

Kind regards...Antonio

**Comment by drugoi** [comment]
No problem, I moved back ES5 syntax and set engine according to Mongoose package.json.

**Comment by drugoi** [comment]
@agorem fixed!

**Pull request merged**
